In [1]:
%load_ext autoreload
%autoreload 2
%load_ext jupyter_black

In [2]:
import polars as pl

In [27]:
path_alpha = "/home/jovyan/data/alpha/data_for_competition/"

In [4]:
path_alfa = "/home/jovyan/data/tabseq/raw/alfa-scoring-trx/"

In [30]:
! ls $path_alpha/train_transactions_contest/train_transactions_contest

part_000_0_to_23646.parquet	   part_025_537037_to_557423.parquet
part_001_23647_to_47415.parquet    part_026_557424_to_576136.parquet
part_002_47416_to_70092.parquet    part_027_576137_to_595745.parquet
part_003_70093_to_92989.parquet    part_028_595746_to_615602.parquet
part_004_92990_to_115175.parquet   part_029_615603_to_635004.parquet
part_005_115176_to_138067.parquet  part_030_635005_to_654605.parquet
part_006_138068_to_159724.parquet  part_031_654606_to_673656.parquet
part_007_159725_to_180735.parquet  part_032_673657_to_696025.parquet
part_008_180736_to_202834.parquet  part_033_696026_to_714545.parquet
part_009_202835_to_224283.parquet  part_034_714546_to_733168.parquet
part_010_224284_to_245233.parquet  part_035_733169_to_752514.parquet
part_011_245234_to_265281.parquet  part_036_752515_to_770940.parquet
part_012_265282_to_285632.parquet  part_037_770941_to_788380.parquet
part_013_285633_to_306877.parquet  part_038_788381_to_805771.parquet
part_014_306878_to_329680.parquet  part_039_805772_to_823299.parquet
part_015_329681_to_350977.parquet  part_040_823300_to_841218.parquet
part_016_350978_to_372076.parquet  part_041_841219_to_859270.parquet
part_017_372077_to_392692.parquet  part_042_859271_to_878521.parquet
part_018_392693_to_413981.parquet  part_043_878522_to_896669.parquet
part_019_413982_to_434478.parquet  part_044_896670_to_916056.parquet
part_020_434479_to_455958.parquet  part_045_916057_to_935131.parquet
part_021_455959_to_477221.parquet  part_046_935132_to_951695.parquet
part_022_477222_to_496751.parquet  part_047_951696_to_970383.parquet
part_023_496752_to_517332.parquet  part_048_970384_to_987313.parquet
part_024_517333_to_537036.parquet  part_049_987314_to_1003050.parquet

In [15]:
! ls $path_alfa

README.md      test_target.csv.gz  train_target.csv.gz
sample.csv.gz  test_transactions   train_transactions

In [7]:
pl.scan_csv(path_alfa + "train_target.csv.gz").count().collect()

shape: (1, 3)
┌────────┬─────────┬────────┐
│ app_id ┆ product ┆ flag   │
│ ---    ┆ ---     ┆ ---    │
│ u32    ┆ u32     ┆ u32    │
╞════════╪═════════╪════════╡
│ 963811 ┆ 963811  ┆ 963811 │
└────────┴─────────┴────────┘

In [8]:
pl.scan_csv(path_alpha + "train_target.csv").count().collect()

shape: (1, 3)
┌────────┬─────────┬────────┐
│ app_id ┆ product ┆ flag   │
│ ---    ┆ ---     ┆ ---    │
│ u32    ┆ u32     ┆ u32    │
╞════════╪═════════╪════════╡
│ 963811 ┆ 963811  ┆ 963811 │
└────────┴─────────┴────────┘

In [32]:
pl.scan_parquet(
    path_alpha + "train_transactions_contest/train_transactions_contest"
).select(pl.len()).collect()

shape: (1, 1)
┌───────────┐
│ len       │
│ ---       │
│ u32       │
╞═══════════╡
│ 270450065 │
└───────────┘

In [33]:
pl.scan_parquet(path_alfa + "train_transactions").select(pl.len()).collect()

shape: (1, 1)
┌───────────┐
│ len       │
│ ---       │
│ u32       │
╞═══════════╡
│ 270450065 │
└───────────┘

In [10]:
df = pl.scan_parquet(path_alfa + "train_transactions").head(1000).collect(engine="gpu")

In [11]:
df.estimated_size(unit="mb")

0.091552734375